ConvertFrom-StringData @'
AadRegistrationSettingsReviewGuideMessage=Dodaj jako dodatkowy identyfikator URI przekierowania ze sciezka lokalna „/signin-oidc” (np. https://wac-portal-site.contoso.com/signin-oidc) w usludze Rejestrowanie aplikacji platformy Azure, aby wlaczyc logowanie w usludze Azure AD.
AadRegistrationSettingsReviewMessage=Ustawienia rejestracji aplikacji platformy Azure musza zostac przejrzane po migracji.
AlreadyPerformedMessage=Wyglada na to, ze migracja zostala juz wykonana.
BindingRemovedMessage=Powiazanie portu HTTP uslugi Windows Admin Center V1 zostalo usuniete. Aby przywrócic usluge Windows Admin Center V1, odinstaluj usluge Windows Admin Center V2 i uzyj polecenia Restore-WACV1Environment.
CannotFindFileMessage=Nie mozna odnalezc pliku w {0}
CompletedEndGuideMessage=Nie pozostalo zadne zadanie.
CompletedMigrationMessage=Migracja zostala ukonczona. Najnowszy stan zostal zapisany w {0} i {1}.
CompletedReviewGuideMessage=Zobacz pozostale zadania {0} z '{1}' pliku.
CompletedReviewMessage=Migracja zostala ukonczona.
ExtensionInstallationReviewGuideMessage=Zlokalizuj i zainstaluj pakiet rozszerzen na tej liscie recznie z poziomu interfejsu uzytkownika Windows Admin Center.
ExtensionInstallationReviewMessage=Pakiet rozszerzenia musi zostac zainstalowany po migracji.
ForcedMessage=Wymuszono powtórzenie migracji. Sprawdz, czego brakowalo w poprzedniej migracji.
MigratedPreInstalledCertifateMessage=Wstepnie zainstalowany certyfikat zostal zmigrowany z programu WACv1.
MigrationStartMessage=Migracja wymaga Windows Admin Center wersja 2 jest wstepnie zainstalowana i skonfigurowana oraz nie zostanie odinstalowana Windows Admin Center V1.
MigrationStartMessage1= 1) W przypadku przeniesienia tego samego numeru portu w trybie uwierzytelniania systemu Windows (NTLM) zostanie usuniete powiazanie portu HTTP uslugi Windows Admin Center V1, a jesli chcesz przywrócic usluge Windows Admin Center V1, mozesz uzyc polecenia Restore-WACV1Environment.
MigrationStartMessage2= 2) Migracja zostanie zresetowana Windows Admin Center V2 dla wybranych kategorii i moze zastapic i usunac biezace dane w Windows Admin Center V2. Istnieja dwie kategorie, takie jak ustawienia i baza danych. Mozesz interakcyjnie pominac jedna kategorie w komunikatach monitu.
MigrationTitle=Migrowanie do Windows Admin Center v2. (NonInteractive: {0})
MigrationWasNotMessage=Migracja nie zostala jeszcze wykonana w systemie.
NoLabel=&Nie
NoServiceMessage=Nie mozna odnalezc lub uzyskac dostepu do uslugi WindowsAdminCenter.
NotFoundV1Message=Narzedzie nie moze odnalezc wstepnie zainstalowanej uslugi Windows Admin Center V1.
NotFoundV2Message=Windows Admin Center V2 nie jest zainstalowany. Musisz recznie przeprowadzic wstepna instalacje Windows Admin Center V2. Uzyj tymczasowego numeru portu, czyli pierwotnego numeru portu przeniesienia migracji do Windows Admin Center V2.
NotHealthV1Message=Nie mozna znalezc prawidlowo wstepnie zainstalowanej uslugi Windows Admin Center V1.
NotStopServiceMessage=Nie mozna zatrzymac uslugi WindowsAdminCenter.
OlderV1Message=Starsza wersja programu Windows Admin Center V1 jest zainstalowana. Przed migracja musisz przeprowadzic uaktualnienie do najnowszej wersji programu Windows Admin Center V1.
OlderV2Message=Starsza wersja programu Windows Admin Center V2 jest zainstalowana. Przed migracja musisz przeprowadzic uaktualnienie do najnowszej wersji programu Windows Admin Center V2.
PathNotJsonMessage=Sciezka musi byc plikiem JSON: {0}
PortMigratedMessage=Zmigrowano powiazanie portów w ramach uwierzytelniania systemu Windows.
ProxySettingsReviewGuideMessage=Przejdz do menu ustawien internetowego serwera proxy w Windows Admin Center interfejsie uzytkownika, aby ponownie skonfigurowac serwer proxy przy uzyciu poswiadczen.
ProxySettingsReviewMessage=Konfiguracja serwera proxy musi zostac sprawdzona po migracji.
QuitAllMessage=Zakoncz wszystkie
QuitLabel=&Zakoncz
QuitMigrationMessage=Zakoncz migracje. Transfer zostal anulowany.
SaveStateV1Message=Zapisano stan Windows Admin Center v1 i V2 do {0}
SelfSignedSubjectNameMessage=Windows Admin Center uzywa certyfikatu z podpisem wlasnym. Migracja uzywa biezacego certyfikatu z podpisem wlasnym, SubjectName={0}.
SkipDatabaseMessage=Pomin aktualizowanie bazy danych.
SkipLabel=&Pomin
SkipSettingsMessage=Pomin aktualizowanie konfiguracji i ustawien.
StatusTitleCannotRepeat=Nie mozna powtórzyc migracji
StatusTitleNotApplicable=Migracja nie ma zastosowania w systemie
StatusTitleNotReady=Migracja nie jest gotowa w systemie
StatusTitlePartial=Migracja zostala czesciowo ukonczona w systemie
StatusTitleReady=Migracja jest gotowa w systemie
StopV1ProceedMessage=Zatrzymaj usluge Windows Admin Center V1 i kontynuuj migracje.
StopWindowsAdminCenterV1Message=Rozpoczecie zapisywania biezacego stanu spowoduje zatrzymanie Windows Admin Center wersji 1.
SureProceedMessage=Czy na pewno chcesz kontynuowac?
TransferReadyMessage=Transferowanie wszystkich danych konfiguracji z wersji V1 ({0}) do wersji V2 ({1})
TransferringStatusMessage=Transferowanie: (Ustawienia: {0}), (Baza danych: {1})
UnexpectedInstallationFolderMessage=Nieoczekiwany katalog instalacji: {0}
UpdateDatabaseMessage=Zaktualizuj i zresetuj baze danych.
UpdateSettingsMessage=Zaktualizuj konfiguracje i ustawienia.
UpdatingDatabaseMessage=Aktualizowanie i resetowanie zawartosci bazy danych. Moze to spowodowac zastapienie i usuniecie istniejacych danych, w tym rejestracji aplikacja systemu Azure z Windows Admin Center V2.
UpdatingSettingsMessage=Aktualizowanie konfiguracji i ustawien. Jesli wybierzesz te opcje, migracja przeniesie numer portu do Windows Admin Center V2.
V1InstallErrorMessage=Platforma Windows Admin Center V1 nie zostala poprawnie zainicjowana, nalezy uzyc jej co najmniej raz po zainstalowaniu lub uaktualnieniu w celu zainicjowania srodowiska. Platforma Windows Admin Center V1 zostanie czesciowo zmigrowana bez ustawien rozszerzen.
V1StoppedMessage=Usluga Windows Admin Center V1 zostala zatrzymana, ale nie zostala odinstalowana.
V2GuideMessage=Przetestuj teraz Windows Admin Center V2. Jesli wszystko jest w porzadku, mozesz odinstalowac Windows Admin Center V1.
V2NotInstalledMessage=Usluga Windows Admin Center V2 nie zostala zainstalowana.
WantToUpdateMessage=Czy chcesz je zaktualizowac?
WebSocketSettingsReviewGuideMessage=Dodaj recznie wszystkie dozwolone zródla w WebSocketAllowedOrigins pliku %Program Files%\\WindowsAdminCenter\\Service\\appsettings.json. Ustaw wszystkie wartosci naglówka zródla dozwolone dla zadan protokolu WebSocket, aby zapobiec przechwyceniu obiektu WebSocket miedzy witrynami. Domyslnie wszystkie zródla sa dozwolone.
WebSocketSettingsReviewMessage=Konfiguracja protokolu WebSocket musi zostac sprawdzona po migracji.
WindowAuthenticationMessage=Usluga Windows Admin Center V2 jest skonfigurowana przy uzyciu uwierzytelniania systemu Windows (NTLM). Migracja portu spowoduje usuniecie powiazania portu z usluga Windows Admin Center V1. Mozesz ja przywrócic, uzywajac polecenia Restore-WACV1Environment, ale po odinstalowaniu uslugi Windows Admin Center V2.
YesLabel=&Tak
'@

# SIG # Begin signature block
# MIIoRgYJKoZIhvcNAQcCoIIoNzCCKDMCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCCa+UPjoR3KMyGc
# FoJLJD4KZ7O3hVIoCbxWAb98Q/8zKaCCDXYwggX0MIID3KADAgECAhMzAAAEBGx0
# Bv9XKydyAAAAAAQEMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjQwOTEyMjAxMTE0WhcNMjUwOTExMjAxMTE0WjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQC0KDfaY50MDqsEGdlIzDHBd6CqIMRQWW9Af1LHDDTuFjfDsvna0nEuDSYJmNyz
# NB10jpbg0lhvkT1AzfX2TLITSXwS8D+mBzGCWMM/wTpciWBV/pbjSazbzoKvRrNo
# DV/u9omOM2Eawyo5JJJdNkM2d8qzkQ0bRuRd4HarmGunSouyb9NY7egWN5E5lUc3
# a2AROzAdHdYpObpCOdeAY2P5XqtJkk79aROpzw16wCjdSn8qMzCBzR7rvH2WVkvF
# HLIxZQET1yhPb6lRmpgBQNnzidHV2Ocxjc8wNiIDzgbDkmlx54QPfw7RwQi8p1fy
# 4byhBrTjv568x8NGv3gwb0RbAgMBAAGjggFzMIIBbzAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQU8huhNbETDU+ZWllL4DNMPCijEU4w
# RQYDVR0RBD4wPKQ6MDgxHjAcBgNVBAsTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEW
# MBQGA1UEBRMNMjMwMDEyKzUwMjkyMzAfBgNVHSMEGDAWgBRIbmTlUAXTgqoXNzci
# tW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3JsMGEG
# CCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3J0
# MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIBAIjmD9IpQVvfB1QehvpC
# Ge7QeTQkKQ7j3bmDMjwSqFL4ri6ae9IFTdpywn5smmtSIyKYDn3/nHtaEn0X1NBj
# L5oP0BjAy1sqxD+uy35B+V8wv5GrxhMDJP8l2QjLtH/UglSTIhLqyt8bUAqVfyfp
# h4COMRvwwjTvChtCnUXXACuCXYHWalOoc0OU2oGN+mPJIJJxaNQc1sjBsMbGIWv3
# cmgSHkCEmrMv7yaidpePt6V+yPMik+eXw3IfZ5eNOiNgL1rZzgSJfTnvUqiaEQ0X
# dG1HbkDv9fv6CTq6m4Ty3IzLiwGSXYxRIXTxT4TYs5VxHy2uFjFXWVSL0J2ARTYL
# E4Oyl1wXDF1PX4bxg1yDMfKPHcE1Ijic5lx1KdK1SkaEJdto4hd++05J9Bf9TAmi
# u6EK6C9Oe5vRadroJCK26uCUI4zIjL/qG7mswW+qT0CW0gnR9JHkXCWNbo8ccMk1
# sJatmRoSAifbgzaYbUz8+lv+IXy5GFuAmLnNbGjacB3IMGpa+lbFgih57/fIhamq
# 5VhxgaEmn/UjWyr+cPiAFWuTVIpfsOjbEAww75wURNM1Imp9NJKye1O24EspEHmb
# DmqCUcq7NqkOKIG4PVm3hDDED/WQpzJDkvu4FrIbvyTGVU01vKsg4UfcdiZ0fQ+/
# V0hf8yrtq9CkB8iIuk5bBxuPMIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkq
# hkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
# IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQG
# EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
# A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQg
# Q29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
# CgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+laUKq4BjgaBEm6f8MMHt03
# a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv2akr
# rnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4Ddato88tt8zpcoRb0Rrrg
# OGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy
# 4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nkkDstrjNYxbc+/jLTswM9
# sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAh
# dCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8k
# A/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTB
# w3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeBe+3W7UvnSSmn
# Eyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90
# lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEAAaOCAe0w
# ggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRIbmTlUAXTgqoXNzcitW2o
# ynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYD
# VR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBDuRQFTuHqp8cx0SOJNDBa
# BgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
# bC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3JsMF4GCCsG
# AQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
# L3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3J0MIGfBgNV
# HSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMuaHRtMEAGCCsG
# AQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkAYwB5AF8AcwB0AGEAdABl
# AG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou09h0ZyKb
# C5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7v0epo/Np22O/IjWll11l
# hJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6
# I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/KmtYSWMfCWluWpiW5IP0
# wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560
# STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBpmLJZiWhub6e3dMNABQam
# ASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGa
# J+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7fQccOKO7eZS/sl/ah
# XJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA
# 9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8MO0ETI7f33Vt
# Y5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr
# /Xmfwb1tbWrJUnMTDXpQzTGCGiYwghoiAgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMw
# EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
# aWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNp
# Z25pbmcgUENBIDIwMTECEzMAAAQEbHQG/1crJ3IAAAAABAQwDQYJYIZIAWUDBAIB
# BQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEO
# MAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIB6PbOHhAs8OT+ZIppVSfn0O
# Fn9g+chZkBs+JHaGFpPdMEIGCisGAQQBgjcCAQwxNDAyoBSAEgBNAGkAYwByAG8A
# cwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20wDQYJKoZIhvcNAQEB
# BQAEggEAhXB0SZz3sGUR0pUYSciuXSP0BniXY0meq8S7/C7zO4z0afMVc4jvXgss
# myA/uxSMqX+mqSUlwNM82L5htsx9FCdN1ZEqXhO0yOOsBK82nTBJk9vZO2dN83Mj
# qzjUtaBhCjj73okRic24cE8NDeW+kKxfVfwDuo9zcNWXi4iCyTHP5wMQbUyvYYUw
# PR+ZuFAP3E++/8MzcJRw8eJkWLS2SHEAlvFPI4YQNYKlgDZpUHDZKIeM/olWDbDN
# uQUzFRWJlbgicjJzqViObSZrkwNBgMYQzvW4GDDg7B7GMhJN2Be3EnKK6vGetAzL
# Y+7Rdphz//kJPzTGKH8hEXntAzbXW6GCF7AwghesBgorBgEEAYI3AwMBMYIXnDCC
# F5gGCSqGSIb3DQEHAqCCF4kwgheFAgEDMQ8wDQYJYIZIAWUDBAIBBQAwggFaBgsq
# hkiG9w0BCRABBKCCAUkEggFFMIIBQQIBAQYKKwYBBAGEWQoDATAxMA0GCWCGSAFl
# AwQCAQUABCBKmaV4icIcpgiJCMUYsfs7jO6KBoxh3/34wZtFqfHLOwIGZ0nWeG2G
# GBMyMDI0MTIwOTE4Mjk1Ni44MTRaMASAAgH0oIHZpIHWMIHTMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJl
# bGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJzAlBgNVBAsTHm5TaGllbGQgVFNTIEVT
# TjozNjA1LTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAg
# U2VydmljZaCCEf4wggcoMIIFEKADAgECAhMzAAAB91ggdQTK+8L0AAEAAAH3MA0G
# CSqGSIb3DQEBCwUAMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9u
# MRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
# b24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwMB4XDTI0
# MDcyNTE4MzEwNloXDTI1MTAyMjE4MzEwNlowgdMxCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xLTArBgNVBAsTJE1pY3Jvc29mdCBJcmVsYW5kIE9w
# ZXJhdGlvbnMgTGltaXRlZDEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNOOjM2MDUt
# MDVFMC1EOTQ3MSUwIwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNl
# MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA0OdHTBNom6/uXKaEKP9r
# PITkT6QxF11tjzB0Nk1byDpPrFTHha3hxwSdTcr8Y0a3k6EQlwqy6ROz42e0R5eD
# W+dCoQapipDIFUOYp3oNuqwX/xepATEkY17MyXFx6rQW2NcWUJW3Qo2AuJ0HOtbl
# SpItQZPGmHnGqkt/DB45Fwxk6VoSvxNcQKhKETkuzrt8U6DRccQm1FdhmPKgDzgc
# fDPM5o+GnzbiMu6y069A4EHmLMmkecSkVvBmcZ8VnzFHTDkGLdpnDV5FXjVObAgb
# SM0cnqYSGfRp7VGHBRqyoscvR4bcQ+CV9pDjbJ6S5rZn1uA8hRhj09Hs33HRevt4
# oWAVYGItgEsG+BrCYbpgWMDEIVnAgPZEiPAaI8wBGemE4feEkuz7TAwgkRBcUzLg
# Q4uvPqRD1A+Jkt26+pDqWYSn0MA8j0zacQk9q/AvciPXD9It2ez+mqEzgFRRsJGL
# tcf9HksvK8Jsd6I5zFShlqi5bpzf1Y4NOiNOh5QwW1pIvA5irlal7qFhkAeeeZqm
# op8+uNxZXxFCQG3R3s5pXW89FiCh9rmXrVqOCwgcXFIJQAQkllKsI+UJqGq9rmRA
# BJz5lHKTFYmFwcM52KWWjNx3z6odwz2h+sxaxewToe9GqtDx3/aU+yqNRcB8w0tS
# XUf+ylN4uk5xHEpLpx+ZNNsCAwEAAaOCAUkwggFFMB0GA1UdDgQWBBTfRqQzP3m9
# PZWuLf1p8/meFfkmmDAfBgNVHSMEGDAWgBSfpxVdAF5iXYP05dJlpxtTNRnpcjBf
# BgNVHR8EWDBWMFSgUqBQhk5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3Bz
# L2NybC9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENBJTIwMjAxMCgxKS5jcmww
# bAYIKwYBBQUHAQEEYDBeMFwGCCsGAQUFBzAChlBodHRwOi8vd3d3Lm1pY3Jvc29m
# dC5jb20vcGtpb3BzL2NlcnRzL01pY3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQQ0El
# MjAyMDEwKDEpLmNydDAMBgNVHRMBAf8EAjAAMBYGA1UdJQEB/wQMMAoGCCsGAQUF
# BwMIMA4GA1UdDwEB/wQEAwIHgDANBgkqhkiG9w0BAQsFAAOCAgEAN0ajafILeL6S
# QIMIMAXM1Qd6xaoci2mOrpR8vKWyyTsL3b83A7XGLiAbQxTrqnXvVWWeNst5YQD8
# saO+UTgOLJdTdfUADhLXoK+RlwjfndimIJT9MH9tUYXLzJXKhZM09ouPwNsrn8YO
# LIpdAi5TPyN8Cl11OGZSlP9r8JnvomW00AoJ4Pl9rlg0G5lcQknAXqHa9nQdWp1Z
# xXqNd+0JsKmlR8tcANX33ClM9NnaClJExLQHiKeHUUWtqyLMl65TW6wRM7XlF7Y+
# PTnC8duNWn4uLng+ON/Z39GO6qBj7IEZxoq4o3avEh9ba43UU6TgzVZaBm8VaA0w
# SwUe/pqpTOYFWN62XL3gl/JC2pzfIPxP66XfRLIxafjBVXm8KVDn2cML9IvRK02s
# 941Y5+RR4gSAOhLiQQ6A03VNRup+spMa0k+XTPAi+2aMH5xa1Zjb/K8u9f9M05U0
# /bUMJXJDP++ysWpJbVRDiHG7szaca+r3HiUPjQJyQl2NiOcYTGV/DcLrLCBK2zG5
# 03FGb04N5Kf10XgAwFaXlod5B9eKh95PnXKx2LNBgLwG85anlhhGxxBQ5mFsJGkB
# n0PZPtAzZyfr96qxzpp2pH9DJJcjKCDrMmZziXazpa5VVN36CO1kDU4ABkSYTXOM
# 8RmJXuQm7mUF3bWmj+hjAJb4pz6hT5UwggdxMIIFWaADAgECAhMzAAAAFcXna54C
# m0mZAAAAAAAVMA0GCSqGSIb3DQEBCwUAMIGIMQswCQYDVQQGEwJVUzETMBEGA1UE
# CBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9z
# b2Z0IENvcnBvcmF0aW9uMTIwMAYDVQQDEylNaWNyb3NvZnQgUm9vdCBDZXJ0aWZp
# Y2F0ZSBBdXRob3JpdHkgMjAxMDAeFw0yMTA5MzAxODIyMjVaFw0zMDA5MzAxODMy
# MjVaMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
# EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNV
# BAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwMIICIjANBgkqhkiG9w0B
# AQEFAAOCAg8AMIICCgKCAgEA5OGmTOe0ciELeaLL1yR5vQ7VgtP97pwHB9KpbE51
# yMo1V/YBf2xK4OK9uT4XYDP/XE/HZveVU3Fa4n5KWv64NmeFRiMMtY0Tz3cywBAY
# 6GB9alKDRLemjkZrBxTzxXb1hlDcwUTIcVxRMTegCjhuje3XD9gmU3w5YQJ6xKr9
# cmmvHaus9ja+NSZk2pg7uhp7M62AW36MEBydUv626GIl3GoPz130/o5Tz9bshVZN
# 7928jaTjkY+yOSxRnOlwaQ3KNi1wjjHINSi947SHJMPgyY9+tVSP3PoFVZhtaDua
# Rr3tpK56KTesy+uDRedGbsoy1cCGMFxPLOJiss254o2I5JasAUq7vnGpF1tnYN74
# kpEeHT39IM9zfUGaRnXNxF803RKJ1v2lIH1+/NmeRd+2ci/bfV+AutuqfjbsNkz2
# K26oElHovwUDo9Fzpk03dJQcNIIP8BDyt0cY7afomXw/TNuvXsLz1dhzPUNOwTM5
# TI4CvEJoLhDqhFFG4tG9ahhaYQFzymeiXtcodgLiMxhy16cg8ML6EgrXY28MyTZk
# i1ugpoMhXV8wdJGUlNi5UPkLiWHzNgY1GIRH29wb0f2y1BzFa/ZcUlFdEtsluq9Q
# BXpsxREdcu+N+VLEhReTwDwV2xo3xwgVGD94q0W29R6HXtqPnhZyacaue7e3Pmri
# Lq0CAwEAAaOCAd0wggHZMBIGCSsGAQQBgjcVAQQFAgMBAAEwIwYJKwYBBAGCNxUC
# BBYEFCqnUv5kxJq+gpE8RjUpzxD/LwTuMB0GA1UdDgQWBBSfpxVdAF5iXYP05dJl
# pxtTNRnpcjBcBgNVHSAEVTBTMFEGDCsGAQQBgjdMg30BATBBMD8GCCsGAQUFBwIB
# FjNodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL0RvY3MvUmVwb3NpdG9y
# eS5odG0wEwYDVR0lBAwwCgYIKwYBBQUHAwgwGQYJKwYBBAGCNxQCBAweCgBTAHUA
# YgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0jBBgwFoAU
# 1fZWy4/oolxiaNE9lJBb186aGMQwVgYDVR0fBE8wTTBLoEmgR4ZFaHR0cDovL2Ny
# bC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0XzIw
# MTAtMDYtMjMuY3JsMFoGCCsGAQUFBwEBBE4wTDBKBggrBgEFBQcwAoY+aHR0cDov
# L3d3dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNSb29DZXJBdXRfMjAxMC0w
# Ni0yMy5jcnQwDQYJKoZIhvcNAQELBQADggIBAJ1VffwqreEsH2cBMSRb4Z5yS/yp
# b+pcFLY+TkdkeLEGk5c9MTO1OdfCcTY/2mRsfNB1OW27DzHkwo/7bNGhlBgi7ulm
# ZzpTTd2YurYeeNg2LpypglYAA7AFvonoaeC6Ce5732pvvinLbtg/SHUB2RjebYIM
# 9W0jVOR4U3UkV7ndn/OOPcbzaN9l9qRWqveVtihVJ9AkvUCgvxm2EhIRXT0n4ECW
# OKz3+SmJw7wXsFSFQrP8DJ6LGYnn8AtqgcKBGUIZUnWKNsIdw2FzLixre24/LAl4
# FOmRsqlb30mjdAy87JGA0j3mSj5mO0+7hvoyGtmW9I/2kQH2zsZ0/fZMcm8Qq3Uw
# xTSwethQ/gpY3UA8x1RtnWN0SCyxTkctwRQEcb9k+SS+c23Kjgm9swFXSVRk2XPX
# fx5bRAGOWhmRaw2fpCjcZxkoJLo4S5pu+yFUa2pFEUep8beuyOiJXk+d0tBMdrVX
# VAmxaQFEfnyhYWxz/gq77EFmPWn9y8FBSX5+k77L+DvktxW/tM4+pTFRhLy/AsGC
# onsXHRWJjXD+57XQKBqJC4822rpM+Zv/Cuk0+CQ1ZyvgDbjmjJnW4SLq8CdCPSWU
# 5nR0W2rRnj7tfqAxM328y+l7vzhwRNGQ8cirOoo6CGJ/2XBjU02N7oJtpQUQwXEG
# ahC0HVUzWLOhcGbyoYIDWTCCAkECAQEwggEBoYHZpIHWMIHTMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJl
# bGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJzAlBgNVBAsTHm5TaGllbGQgVFNTIEVT
# TjozNjA1LTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAg
# U2VydmljZaIjCgEBMAcGBSsOAwIaAxUAb28KDG/xXbNBjmM7/nqw3bgrEOaggYMw
# gYCkfjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
# BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYD
# VQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDANBgkqhkiG9w0BAQsF
# AAIFAOsBg4MwIhgPMjAyNDEyMDkxNDU2MDNaGA8yMDI0MTIxMDE0NTYwM1owdzA9
# BgorBgEEAYRZCgQBMS8wLTAKAgUA6wGDgwIBADAKAgEAAgIYmwIB/zAHAgEAAgIU
# JTAKAgUA6wLVAwIBADA2BgorBgEEAYRZCgQCMSgwJjAMBgorBgEEAYRZCgMCoAow
# CAIBAAIDB6EgoQowCAIBAAIDAYagMA0GCSqGSIb3DQEBCwUAA4IBAQBAOBxB2H7J
# S15ZPywgHTwEulklOfk70B7hbHbO3fAfW7NlsC8i6v5ZF97nntzQ/Kk0KWwaUipB
# zyO9g2t1Tpyw+mTD91e+Qe8MrMbs5co/wX7tyaIgXhOAPAXR7us7aUi2aERAiJfx
# x/Z9XY6Pb6TKzQ6p0u3uR62Wkxk856zzdEILm/69dsdYaERsAMcFmHuN/oEc5J4U
# ApAUzs8Pv/T1S9O2HPv7YGZHDKnnq2Si8FBnFdwW6lPP2Unh9guAQHqWm+eJsckf
# 7zRJbxDpxqbMweD0hL67z0Cl/n9p+1pzyQOawDBU0vfQHE6eEWie9gTVbtf20lCO
# J8M+OUx/m/obMYIEDTCCBAkCAQEwgZMwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgT
# Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
# dCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENB
# IDIwMTACEzMAAAH3WCB1BMr7wvQAAQAAAfcwDQYJYIZIAWUDBAIBBQCgggFKMBoG
# CSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAvBgkqhkiG9w0BCQQxIgQgDWXA0j/u
# K61oTAgByrPaPnNW+xSTOWUJFHigG/FgL/YwgfoGCyqGSIb3DQEJEAIvMYHqMIHn
# MIHkMIG9BCAh2pjaa3ca0ecYuhu60uYHP/IKnPbedbVQJ5SoIH5Z4jCBmDCBgKR+
# MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdS
# ZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMT
# HU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAAB91ggdQTK+8L0AAEA
# AAH3MCIEIOQmunBMJAjtRgRrf1Qo7ScDFij+Nwi5Aoh7WGNwMEsdMA0GCSqGSIb3
# DQEBCwUABIICAD3mYeGAp+42Avfab5fL8ytvwFBJhYn5H05Qw6H3pqumYd/T5RLi
# eTokhmZdytJwMkjeiASUcRNXt6SfQ6XM9cnkpLxWPlgLdmwyNlz/PRXMHQSUnFKB
# u8RxLpITxsKCaq82W1gju4AdL+QdHW2T3jbbtQ3RlKiUpnxmUtoocyFh8e8m7Pmr
# cLes9TqEy7LcXyopb13LUaXFpKDoYsxbcILto7LLsBi5SByGM5Yo9kwGNU0Vn3AA
# pDKMkMBpg12H/kzElDvY8MlFcDglvZRUcj6znseNb2C/iAOz0wVt6MTFX+a1iqCX
# fGPAPWiYt35XWNd8SXJQBbgBUEd4tRoM/VPRqpXIChsYBQGokRhO6eu90ozlwIF3
# YfCz5v97VosT4x6MR2WhsaTLEeVEh2JSbba5TcqfdNNc11jdDa69kssCXCFKN/U4
# FccgqAufMcUMaG0YBbNjT67aGG3+eczo5tMs6LV+eRWoqKIItjUy+uvvx0fLICj4
# oaVwzGNgGLIzOLi8l18+aFYgK8usZDkxbTiuQZAQVXQnq60IMmeypo/Ak9B5buNx
# bq7tMjbE3Ub0nP3zd3RwiTT1DdnQjHyFXq7vPGdN53aIh2uLPVuii29uZpGyyANP
# ZbosAz93CUnSsWSHUjjeYrnjg042ke5hybHvsUgY9GFwfP5bBmNo94/p
# SIG # End signature block
